### ISSUE TITLE
Better error for missing comma in arglist

### ISSUE THREAD

**Issue by jariji** [JuliaLang/JuliaSyntax.jl#411] opened 2024-02-04 22:45 UTC
```jl
julia> f(foo, bar baz, quux)
ERROR: ParseError:
# Error @ 

f(foo, bar baz, quux)
#          └───────┘ ── Expected `)`
```

It says expected `)` but the problem is actually a missing `,` and adding a `)` wouldn't help. Maybe it could suggest several options instead of just one.

**Comment by Tortar** [comment] 2024-05-02 00:35
duplicate of https://github.com/JuliaLang/julia/issues/52285

**Closed** 2024-05-02 00:45 UTC

**Comment by Tortar** [comment] 2024-05-02 01:20
Actually already fixed (see https://github.com/JuliaLang/julia/issues/52285) but we are still on an old version of JuliaSyntax in Julia :(
