### ISSUE TITLE
`Expected ')'` suggestion where maybe an `Expected ','` would be prefred

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/JuliaSyntax.jl#321] opened 2023-06-30 09:41 UTC
```julia
julia> f(x y)
ERROR: ParseError:
# Error @ REPL[2]:1:5
f(x y)
#   ╙ ── Expected `)`
```

The number of parentheses is balanced here so it seems more likely that suggesting a `,` is preferable, or?

**Comment by c42f** [comment] 2023-07-01 17:50
Yes, we should be able to do better here :+1: Duplicate of #313

**Closed by c42f** 2023-07-01 17:50 UTC
