### ISSUE TITLE
'\ \\' returns ErrorVal

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/JuliaSyntax.jl#138] opened 2022-11-01 15:45 UTC
I think this should error instead of leaking the error value into the REPL
Flisp parser:
```
julia> '\ \\'
ERROR: syntax: invalid escape sequence
```

JuliaSyntax
```
julia> '\ \\'
✘

julia> typeof(ans)
JuliaSyntax.ErrorVal
```

**Comment by c42f** [comment] 2022-11-02 11:35
Yes indeed. This is an almost-duplicate of #109, the fix will be the same.

**Closed** 2022-11-18 08:11 UTC
Labels: bug, duplicate
